title: Shirley Redroban # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br>
  Msc. in Economics 
  <br><br>
  Research Associate at Clapes UC. Previously in Jpal-Lac. 
  <br><br>
  <a href="https://www.linkedin.com/in/shirley-redroban/">View my LinkedIn Profile</a> 
  <a href="https://drive.google.com/file/d/1wldWyDAZVwzfmfGx-8iOvACJuG4FztHA/view?usp=sharing">View my CV</a> 

  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
